### ISSUE TITLE
Public website (EPIC)

### ISSUE THREAD

**Issue by vgeorge** [osmforcities/osmforcities#26]
This is an epic ticket to track the implementation of the first version of the public website. We aim to provide stats for all cities of Brazil and a diff browser for datasets.

In #24 we added a scaffold website. The list of tasks is:

- [ ] Add readme on how to run the development server locally
- [ ] Display city stats
- [ ] Add diff viewer for datasets
- [ ] Add about page and contact info
- [ ] Use 'federative-unit' instead of 'state' for Brazilian regions

**Comment by vgeorge** [comment]
🔒 **Closing as part of the v0 deprecation**

This issue is related to the first version of *OSM for Cities* (v0), which has now been officially deprecated. The processing pipeline got too complex to maintain, and we're focusing on a simpler rewrite based on Overpass.

More details here: [https://github.com/osmforcities/osmforcities/issues/62](https://github.com/osmforcities/osmforcities/issues/62)
